---
title: "Lab10_PatrickIhejirika"
author: "Patrick Ihejirika"
date: "11/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())

library(data.table)
library(readxl)
library(tidyverse)
all_data <- read_csv("~/downloads/stroop_stand.csv")
```



#The re-analysis should focus only on Experiment 3. There are three main goals

```{r}
#Reproduce as much of the analysis as possible using only paired-sample t-tests. Note, the authors reported a 2x2 repeated measures ANOVA, but consider how the same questions could be answered by t-tests (2 points)


#Difference between sitting
sit_difference = ((all_data$congruent_sit) - (all_data$incongruent_sit))
mean_sit_difference = mean(sit_difference)

variance1 = c()
for (i in 1:length(sit_difference)) {
  variance1[i] = (sit_difference[i] - (mean_sit_difference))^2
}

Std_error_difference = sqrt((sum(variance1) / (length(variance1) - 1))/length(variance1))
t_df1 = mean_sit_difference/Std_error_difference 
t_df1


#Difference between standing
stand_difference = ((all_data$congruent_stand) - (all_data$incongruent_stand))
mean_stand_difference = mean(stand_difference)

variance2 = c()
for (i in 1:length(stand_difference)) {
  variance2[i] = (stand_difference[i] - (mean_stand_difference))^2
}

Std_error_difference2 = sqrt((sum(variance2) / (length(variance2) - 1))/length(variance2))
t_df2 = mean_stand_difference/Std_error_difference2 
t_df2
```


```{r}
#Reproduce a graph of the means, like shown in the paper (2 points)
all_data$incongruent_stand


congruent_stand = mean(all_data$congruent_stand)
incongruent_stand = mean(all_data$incongruent_stand)
congruent_sit = mean(all_data$congruent_sit)
incongruent_sit = mean(all_data$incongruent_sit)

position = rep(c("Stand", "Sit"), each = 2)
congruency = rep(c("Congruent", "Incongruent"), times = 2)
Averages = c(congruent_stand, incongruent_stand, congruent_sit, incongruent_sit)

df = data.frame(position, congruency, Averages)

p <- ggplot(data=df, aes(x=position, y=Averages, fill=congruency)) +
geom_bar(stat="identity", color="black", position=position_dodge())

p
```

```{r}
#Present a power-curve analysis for the design. (2 points)


effect_sizes <- seq(0,1.5,.1)
prop_significant <-c()

for(i in 1:length(effect_sizes)){
  sim_ps <- replicate(1000, t.test(replicate(50, mean(rnorm(1, effect_sizes[i], 1))),
                                             mu = 0)$p.value)
  
  prop_significant[i] <- length(sim_ps[sim_ps < .05])/1000
}

plot_df <- data.frame(effect_sizes,
                      prop_significant)

ggplot(plot_df, aes(x=effect_sizes,y=prop_significant))+
  geom_line() +
  geom_point() +
  scale_x_continuous(breaks=seq(0,1.5,.1))+
  scale_y_continuous(breaks=seq(0,1,.1)) +
  ylab("Proportion Significant")


```

